apiVersion: v1
kind: Service
metadata:
  name: demo-chat-service
  namespace: default
  labels:
    app: demo-chat
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: demo-chat
  type: LoadBalancer